fix: Formatting
Signed-off-by: appkins <nbatkins@gmail.com>

diff --git a/nanokvm/overlay/etc/ipmi/ipmi_sim_chassiscontrol b/nanokvm/overlay/etc/ipmi/ipmi_sim_chassiscontrol
--- a/nanokvm/overlay/etc/ipmi/ipmi_sim_chassiscontrol
+++ b/nanokvm/overlay/etc/ipmi/ipmi_sim_chassiscontrol
@@ -26,111 +26,105 @@ prog=$0
 
 device=$1
 if [ "${device}" = "" ]; then
-    echo "No device given"
-    exit 1;
+  echo "No device given"
+  exit 1
 fi
 shift
 
 op=$1
 if [ "${op}" = "" ]; then
-    echo "No operation given"
-    exit 1
+  echo "No operation given"
+  exit 1
 fi
 shift
 
 do_get() {
-    while [ "$1" != "" ]; do
-	case $1 in
-	    power)
-		val="$(ssh -q root@10.0.92.76 swctrl poe show id 25 | tail -n1 | awk '{$1=$1;print}' | cut -d' ' -f2 | grep -q "^Auto$" && echo 1 || echo 0)"
-		;;
+  while [ "$1" != "" ]; do
+    case $1 in
+    power)
+      val="$(ssh -q root@10.0.92.76 swctrl poe show id 25 | tail -n1 | awk '{$1=$1;print}' | cut -d' ' -f2 | grep -q "^Auto$" && echo 1 || echo 0)"
+      ;;
 
-	    boot)
-		val=default
-		;;
+    boot)
+      val=default
+      ;;
 
-	    # Note that reset has no get
+    # Note that reset has no get
 
-	    *)
-		echo "Invalid parameter: $1"
-		exit 1
-		;;
-	esac
+    *)
+      echo "Invalid parameter: $1"
+      exit 1
+      ;;
+    esac
 
-	echo "$1:${val}"
-	shift
-    done
+    echo "$1:${val}"
+    shift
+  done
 }
 
 do_set() {
-    while [ "$1" != "" ]; do
-	parm="$1"
-	shift
-	if [ "$1" = "" ]; then
-	    echo "No value present for parameter ${parm}"
-	    exit 1
-	fi
-	val="$1"
-	shift
+  while [ "$1" != "" ]; do
+    parm="$1"
+    shift
+    if [ "$1" = "" ]; then
+      echo "No value present for parameter ${parm}"
+      exit 1
+    fi
+    val="$1"
+    shift
 
-	case ${parm} in
-	    power)
-		;;
+    case ${parm} in
+    power) ;;
 
-	    reset)
-		;;
+    reset) ;;
 
-	    boot)
-		case ${val} in
-		    none)
-			;;
-		    pxe)
-			;;
-	            cdrom)
-			;;
-		    bios)
-		        ;;
-		    default)
-	               ;;
-		    *)
-			echo "Invalid boot value: ${val}"
-			exit 1
-			;;
-		esac
-		;;
+    boot)
+      case ${val} in
+      none) ;;
+      pxe) ;;
+      cdrom) ;;
+      bios) ;;
+      default) ;;
+      *)
+        echo "Invalid boot value: ${val}"
+        exit 1
+        ;;
+      esac
+      ;;
 
-            identify)
-		interval=${val}
-		force=$1
-		shift
-		;;
+    identify)
+      interval=${val}
+      force=$1
+      shift
+      ;;
 
-	    *)
-		echo "Invalid parameter: ${parm}"
-		exit 1
-		;;
-	esac
-    done
+    *)
+      echo "Invalid parameter: ${parm}"
+      exit 1
+      ;;
+    esac
+  done
 }
 
 do_check() {
-    # Check is not supported for chassis control
-    exit 1
+  # Check is not supported for chassis control
+  exit 1
 }
 
 case ${op} in
-    get)
-	do_get $@
-	;;
-    set)
-	do_set $@
-	;;
+get)
+  do_get $@
+  ;;
+set)
+  do_set $@
+  ;;
 
-    check)
-	do_check $@
-	;;
+check)
+  do_check $@
+  ;;
 
 *)
-	echo "Unknown operation: ${op}"
-	exit 1
+  echo "Unknown operation: ${op}"
+  exit 1
+  ;;
 esac
diff --git a/nanokvm/overlay/etc/ipmi/ipmi_sim_lancontrol b/nanokvm/overlay/etc/ipmi/ipmi_sim_lancontrol
--- a/nanokvm/overlay/etc/ipmi/ipmi_sim_lancontrol
+++ b/nanokvm/overlay/etc/ipmi/ipmi_sim_lancontrol
@@ -39,178 +39,167 @@ prog=$0
 
 device=$1
 if [ "${device}" = "" ]; then
-    echo "No device given"
-    exit 1;
+  echo "No device given"
+  exit 1
 fi
 shift
 
 op=$1
 if [ "${op}" = "" ]; then
-    echo "No operation given"
-    exit 1
+  echo "No operation given"
+  exit 1
 fi
 shift
 
 do_get() {
-    while [ "$1" != "" ]; do
-	case $1 in
-	    ip_addr)
-		val=$(ifconfig "${device}" | grep '^ *inet addr:' | tr ':' ' ' | sed 's/.*inet addr \([0-9.]*\).*$/\1/')
-		if [ "${val}" = "" ]; then
-		    val="0.0.0.0"
-		fi
-		;;
+  while [ "$1" != "" ]; do
+    case $1 in
+    ip_addr)
+      val=$(ifconfig "${device}" | grep '^ *inet addr:' | tr ':' ' ' | sed 's/.*inet addr \([0-9.]*\).*$/\1/')
+      if [ "${val}" = "" ]; then
+        val="0.0.0.0"
+      fi
+      ;;
 
-	    ip_addr_src)
-		val=$(grep "iface ${device} inet" /etc/network/interfaces | tr ' ' '\t' | tr -s '\t' '\t' | cut -f 4)
-		case "x${val}" in
-		    xstatic)
-			;;
-		    xdhcp)
-			;;
-		    *)
-			val="unknown"
-			;;
-		esac
-		;;
+    ip_addr_src)
+      val=$(grep "iface ${device} inet" /etc/network/interfaces | tr ' ' '\t' | tr -s '\t' '\t' | cut -f 4)
+      case "x${val}" in
+      xstatic) ;;
+      xdhcp) ;;
+      *)
+        val="unknown"
+        ;;
+      esac
+      ;;
 
-	    mac_addr)
-		val=$(ifconfig "${device}" | grep 'HWaddr' | sed 's/.*HWaddr \([0-9a-f:]*\).*$/\1/')
-		if [ "${val}" = "" ]; then
-		    val="00:00:00:00:00:00"
-		fi
-		;;
+    mac_addr)
+      val=$(ifconfig "${device}" | grep 'HWaddr' | sed 's/.*HWaddr \([0-9a-f:]*\).*$/\1/')
+      if [ "${val}" = "" ]; then
+        val="00:00:00:00:00:00"
+      fi
+      ;;
 
-	    subnet_mask)
-		val=$(ifconfig "${device}" | grep '^ *inet addr:' | tr ':' ' ' | sed 's/.*Mask \([0-9.]*\).*$/\1/')
-		if [ "${val}" = "" ]; then
-		    val="0.0.0.0"
-		fi
-		;;
+    subnet_mask)
+      val=$(ifconfig "${device}" | grep '^ *inet addr:' | tr ':' ' ' | sed 's/.*Mask \([0-9.]*\).*$/\1/')
+      if [ "${val}" = "" ]; then
+        val="0.0.0.0"
+      fi
+      ;;
 
-	    default_gw_ip_addr)
-		val=$(route -n | grep '^0\.0\.0\.0' | grep 'eth1$' | tr ' ' '\t' | tr -s '\t' '\t' | cut -f 2)
-		if [ "${val}" = "" ]; then
-		    val="0.0.0.0"
-		fi
-		;;
+    default_gw_ip_addr)
+      val=$(route -n | grep '^0\.0\.0\.0' | grep 'eth1$' | tr ' ' '\t' | tr -s '\t' '\t' | cut -f 2)
+      if [ "${val}" = "" ]; then
+        val="0.0.0.0"
+      fi
+      ;;
 
-	    default_gw_mac_addr)
-		val=$(route -n | grep '^0\.0\.0\.0' | grep "${device}\$" | tr ' ' '\t' | tr -s '\t' '\t' | cut -s -f 2)
-		if [ "${val}" = "" ]; then
-		    val="00:00:00:00:00:00"
-		else
-		    val=$(arp -n "${val}" | grep "^${val}" | tr ' ' '\t' | tr -s '\t' '\t' | cut -f 3 | tr -d -c '0-9a-f:')
-		    if [ "${val}" = "" ]; then
-			val="00:00:00:00:00:00"
-		    fi
-		fi
-		;;
+    default_gw_mac_addr)
+      val=$(route -n | grep '^0\.0\.0\.0' | grep "${device}\$" | tr ' ' '\t' | tr -s '\t' '\t' | cut -s -f 2)
+      if [ "${val}" = "" ]; then
+        val="00:00:00:00:00:00"
+      else
+        val=$(arp -n "${val}" | grep "^${val}" | tr ' ' '\t' | tr -s '\t' '\t' | cut -f 3 | tr -d -c '0-9a-f:')
+        if [ "${val}" = "" ]; then
+          val="00:00:00:00:00:00"
+        fi
+      fi
+      ;;
 
-	    backup_gw_ip_addr)
-		val="0.0.0.0"
-		;;
+    backup_gw_ip_addr)
+      val="0.0.0.0"
+      ;;
 
-	    backup_gw_mac_addr)
-		val="00:00:00:00:00:00"
-		;;
+    backup_gw_mac_addr)
+      val="00:00:00:00:00:00"
+      ;;
 
-	    *)
-		echo "Invalid parameter: $1"
-		exit 1
-		;;
-	esac
+    *)
+      echo "Invalid parameter: $1"
+      exit 1
+      ;;
+    esac
 
-	echo "$1:${val}"
-	shift
-    done
+    echo "$1:${val}"
+    shift
+  done
 }
 
 do_set() {
-    while [ "$1" != "" ]; do
-	parm="$1"
-	shift
-	if [ "$1" = "" ]; then
-	    echo "No value present for parameter ${parm}"
-	    exit 1
-	fi
-	val="$1"
-	shift
+  while [ "$1" != "" ]; do
+    parm="$1"
+    shift
+    if [ "$1" = "" ]; then
+      echo "No value present for parameter ${parm}"
+      exit 1
+    fi
+    val="$1"
+    shift
 
-	case ${parm} in
-	    ip_addr)
-		;;
+    case ${parm} in
+    ip_addr) ;;
 
-	    ip_addr_src)
-		;;
+    ip_addr_src) ;;
 
-	    mac_addr)
-		;;
+    mac_addr) ;;
 
-	    subnet_mask)
-		;;
+    subnet_mask) ;;
 
-	    default_gw_ip_addr)
-		;;
+    default_gw_ip_addr) ;;
 
-	    default_gw_mac_addr)
-		;;
+    default_gw_mac_addr) ;;
 
-	    backup_gw_ip_addr)
-		;;
+    backup_gw_ip_addr) ;;
 
-	    backup_gw_mac_addr)
-		;;
+    backup_gw_mac_addr) ;;
 
-	    *)
-		echo "Invalid parameter: $1"
-		exit 1
-		;;
-	esac
-    done
+    *)
+      echo "Invalid parameter: $1"
+      exit 1
+      ;;
+    esac
+  done
 }
 
 do_check() {
-    while [ "$1" != "" ]; do
-	parm="$1"
-	shift
-	case ${parm} in
-	    ip_addr_src)
-		# We only support static and dhcp IP address sources
-		case $1 in
-		    static)
-			;;
-		    dhcp)
-			;;
-		    *)
-			echo "Invalid ip_addr_src: $1"
-			exit 1
-			;;
-		esac
-		;;
+  while [ "$1" != "" ]; do
+    parm="$1"
+    shift
+    case ${parm} in
+    ip_addr_src)
+      # We only support static and dhcp IP address sources
+      case $1 in
+      static) ;;
+      dhcp) ;;
+      *)
+        echo "Invalid ip_addr_src: $1"
+        exit 1
+        ;;
+      esac
+      ;;
 
-	    *)
-		echo "Invalid parameter: ${parm}"
-		exit 1
-		;;
-	esac
-	shift
-    done
+    *)
+      echo "Invalid parameter: ${parm}"
+      exit 1
+      ;;
+    esac
+    shift
+  done
 }
 
 case ${op} in
-    get)
-	do_get $@
-	;;
-    set)
-	do_set $@
-	;;
+get)
+  do_get "$@"
+  ;;
+set)
+  do_set "$@"
+  ;;
 
-    check)
-	do_check $@
-	;;
+check)
+  do_check "$@"
+  ;;
 
 *)
-	echo "Unknown operation: ${op}"
-	exit 1
+  echo "Unknown operation: ${op}"
+  exit 1
+  ;;
 esac
